### ISSUE TITLE
Replaces `/index.html` with `::`

### ISSUE THREAD

**Issue by jyn514** [poliorcetics/cargo-intraconv#10]
```
-//! [`env_logger`]: env_logger/index.html
+//! [`env_logger`]: env_logger::
```

**Comment by poliorcetics** [comment]
Doesn't this interfere with #6 ? I'm completely okay with adding it, I'm just not sure about how rustdoc handle those cases, I'll do tests later.

**Comment by jyn514** [comment]
`env_logger` will link to the env_logger crate if it's in scope. `env_logger::` is not valid syntax.

**Comment by poliorcetics** [comment]
Ahh, my bad, you're saying `intraconv` modifies the original link incorrectly ? I'll fix it then

**Comment by poliorcetics** [comment]
I'm not seeing it in tests:

```rust
            let line = "/// [`string`]: string/index.html\n";
            let res = ctx.transform_line(line.into());
            assert_eq!(line, res);
            assert_deleted(res);
```

**Comment by jyn514** [comment]
It's fixed on master, probably you fixed it in the branch you pushed.
