### ISSUE TITLE
Regression: adds lots of new whitespace

### ISSUE THREAD

**Issue by jyn514** [poliorcetics/cargo-intraconv#11]
This is a regression from yesterday.

```
tracing-appender/src/inner.rs
=============================

    1:  "use std::io::{BufWriter, Write};
"
        "use std::io::{BufWriter, Write};
"

    2:  "
"
        "
"

    3:  "
"
        "
"

    4:  "
"
        "
"
```
```
diff --git a/tracing-appender/src/inner.rs b/tracing-appender/src/inner.rs
index f1e0fe0..6ade116 100644
--- a/tracing-appender/src/inner.rs
+++ b/tracing-appender/src/inner.rs
@@ -1,96 +1,768 @@
 use std::io::{BufWriter, Write};
+
+
+
+
+
+
+
```

**Comment by poliorcetics** [comment]
Oh. I must have missed a `\n` somewhere, I'll check

**Comment by poliorcetics** [comment]
Ok, should be fixed with `3fe59eb`:

<img width="718" alt="Screenshot 2020-10-07 at 16 06 21" src="https://user-images.githubusercontent.com/7951708/95341865-0c1a0000-08b7-11eb-8e64-2e13f3a1d5d4.png">

If this is fixed on your side you can close :). Thanks for the report !

**Comment by jyn514** [comment]
> Deleted local link

Wait, why would that link be deleted? I want to keep those.

**Comment by jyn514** [comment]
Oh because it would be the same after it was replaced :) Can you change the message to say that?
