### ISSUE TITLE
Improve item transformation with special characters

### ISSUE THREAD

**Issue by poliorcetics** [poliorcetics/cargo-intraconv#13]
For example macros can be suffixed with `!`, functions and methods with `()` and primitives can be prefixed `primitive@`.

See [this PR for some background](https://github.com/rust-lang/rust/pull/75567#issuecomment-674427783).

**Comment by jyn514** [comment]
I wrote this up already, so pasting here:

Currently, `intraconv` will replace all items with only their name:

```
-//! [instrument]: attr.instrument.html
```

This leads to ambiguity if the same name is present in multiple namespaces:

```
warning: `instrument` is both a function and an attribute macro
 --> tracing-attributes/src/lib.rs:5:23
  |
5 | //! [`#[instrument]`][instrument] procedural macro attribute.
  |                       ^^^^^^^^^^ ambiguous link
```

It would be great to add a disambiguator so these didn't have to be fixed manually. The following transformations should work:

```
"mod" => "mod@", // this one needs to be different because of primitives
"struct" | "enum" | "trait" | "union" | "type" |  => "type@", // technically these should use struct@, etc. but it's non-idiomatic to use a lowercase name so it shouldn't come up in practice
"const" | "static" | "value" => "value@",
"fn" => "()",
"derive" | "attr" => "macro@",
"macro" => "!",
```

There might be more I haven't thought of but this should hit the common cases. Places to look at in rustdoc:
https://github.com/rust-lang/rust/blob/master/src/librustdoc/passes/collect_intra_doc_links.rs#L1281-L1320
https://github.com/rust-lang/rust/blob/master/src/librustdoc/formats/item_type.rs#L127-L156

**Comment by poliorcetics** [comment]
I just pushed a fix for it, don't hesitate to open a new issue/reopen the existing one if you find failing cases.
