### ISSUE TITLE
Support for docs.rs links

### ISSUE THREAD

**Issue by jyn514** [poliorcetics/cargo-intraconv#17]
I'd like to turn this link:
```rust
/// [`Span`]: https://docs.rs/tracing-core/latest/tracing_core/span/index.html
```
into this one:
```
/// [`Span`]: tracing_code::span
```
I _think_ this should be fairly easy to add: if the URL starts with `https://docs.rs`, strip the host and first 2 path segments, then treat it like a normal link.

**Comment by poliorcetics** [comment]
Maybe a new option for this ? I can't think of some situation where one might want to link to `docs.rs` without having the linked crate as a dependency, but there might be one.

Maybe have the option to turn it off and have it on by default is better.

**Comment by poliorcetics** [comment]
This should work now, and with lots of tests. :)
