### ISSUE TITLE
Run on all crates in the workspace

### ISSUE THREAD

**Issue by jyn514** [poliorcetics/cargo-intraconv#18]
Currently, the way I run `intraconv` is like this:

```
for crate in tracing*; do cargo intraconv $crate/**/*.rs -c $(echo $crate | tr - _) -a; done
```

It would be nice to have this built-in. In particular, this

- Runs on all crates in the workspace
- Sets the crate name appropriately
- Runs on all files within a crate

**Comment by jyn514** [comment]
And a stretch feature: don't replace `docs.rs/crate/...` unless the crate is in `Cargo.toml`.

**Comment by jyn514** [comment]
If you like, I could publish the logic for this as a small crate: https://github.com/deadlinks/cargo-deadlinks/blob/master/src/main.rs#L130-L174. Or you could just copy the logic yourself.

**Comment by poliorcetics** [comment]
I'll copy the logic, thanks a lot for the link !
