### ISSUE TITLE
Convert doc.rust-lang.org to intra-doc links

### ISSUE THREAD

**Issue by jyn514** [poliorcetics/cargo-intraconv#22]
Similar to #17. I'd like these links:

 ```
tracing/src/lib.rs://! [fmt]: https://doc.rust-lang.org/std/fmt/#usage
tracing/src/lib.rs://! [`libstd`]: https://doc.rust-lang.org/std/index.html
tracing/src/lib.rs://! [`liballoc`]: https://doc.rust-lang.org/alloc/index.html
```

to be turned  into these:

```
tracing/src/lib.rs://! [fmt]: std::fmt#usage
tracing/src/lib.rs://! [`libstd`]: std
tracing/src/lib.rs://! [`liballoc`]: alloc
```

In an ideal world:

- `/nightly`, /beta, and /stable would be stripped (e.g. https://doc.rust-lang.org/nightly/std/primitive.str.html)
- leading paths that aren't crates would be ignored (e.g. https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/enum.TyKind.html or https://doc.rust-lang.org/book/ch04-01-what-is-ownership.html#the-stack-and-the-heap)

**Comment by poliorcetics** [comment]
> * leading paths that aren't crates would be ignored (e.g. https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/enum.TyKind.html ...

What isn't a valid crate here ? I can certainly extract `rustc_hir::TyKind`.

**Comment by jyn514** [comment]
Hmm, I was thinking of this in the context of user programs, but I guess if you're linking to nightly-rustc it's likely you're already in the compiler source tree somewhere. So it would then make sense to convert this.

**Comment by poliorcetics** [comment]
Do you know if there is a list of the possible urls for docs coming from https://doc.rust-lang.org/ somewhere (The leading parts, like `nightly|stable|...` and `std|alloc|nightly-rustc|...`) ?

**Comment by jyn514** [comment]
I don't know of an authoritative list, but the prefixes are `nightly|stable|beta|1.xx.x` and the crates are `std|alloc|core|proc_macro|test`. I _think_ nightly-rustc is the only special case, you can treat any directory after that as a crate.

**Comment by poliorcetics** [comment]
Should be fixed now. I'll publish a new version of `intraconv` when #18 and #21 are closed
