### ISSUE TITLE
[stretch] convert <a href=""> to intra-doc links

### ISSUE THREAD

**Issue by jyn514** [poliorcetics/cargo-intraconv#24]
Feel free to close this as wontfix.

Before:

```
    /// <strong>Note</strong>: The fields associated with a span are part of its
    /// <a href="../struct.Metadata.html"><code>Metadata</code></a>.
    /// The <a href="../struct.Metadata.html"><code>Metadata</code></a>. describing a particular
    /// span is constructed statically when the span is created and cannot be extended later to
```

After:

```
    /// <strong>Note</strong>: The fields associated with a span are part of its
    ///
    /// [`Metadata`](super::Metadata). The [Metadata](super::Metadata) describing a particular
    /// span is constructed statically when the span is created and cannot be extended later to
```

The extra blank line _may_ not be necessary depending on the markdown parser, I haven't tested.

**Comment by poliorcetics** [comment]
I'm not confident **at all** parsing HTML through regexes. I'll fix the other issues before even thinking about that one.

Are HTML links used at lot ?

**Comment by jyn514** [comment]
No, there were about 10/~200 links in tracing that used this, and I'd expect tracing to use them more than most codebases. I'm ok if you say this is out of scope, rustdoc doesn't parse these either and I had to make pretty significant changes to make them work: https://github.com/tokio-rs/tracing/pull/1078/commits/6171c831a2e8ce918c4e6a0a30f1e0f6987f22af

**Comment by poliorcetics** [comment]
I don't think parsing HTML is in scope for `intraconv`, especially since the Markdown syntax for links is available. I won't fix, thanks for the suggestion anyway !
