### ISSUE TITLE
docs.rs/crate/x is treated as if crate/ is a crate

### ISSUE THREAD

**Issue by jyn514** [poliorcetics/cargo-intraconv#26]
```
/home/joshua/src/rust/tracing/tracing-subscriber/src/registry/sharded.rs
========================================================================

   39:  "/// [slab]: https://docs.rs/crate/sharded-slab/"
        "/// [slab]: crate"
```
This can't be converted automatically, `/crate/sharded-slab` is not the target of any intra-doc link.

**Comment by poliorcetics** [comment]
It's not very hard to fix this, just a bit long because I'll to write more tests and move some things around

**Comment by poliorcetics** [comment]
New output:

```
/Users/alexis/Projects/rust/tracing/tracing-subscriber/src/registry/sharded.rs
==============================================================================

   40:  "    /// [slab]: https://docs.rs/crate/sharded-slab/"
        "    /// [slab]: sharded_slab"
```

**Comment by jyn514** [comment]
@poliorcetics that's not the right behavior: now the link goes to docs.rs/sharded-slab (the documentation, not the crate page). This link can't be converted at all.

**Comment by poliorcetics** [comment]
ohhh, I thought the `/crate/` prefix had no special meaning. I'll fix it quickly !

**Comment by jyn514** [comment]
For comparison, this is the documentation page: 
![image](https://user-images.githubusercontent.com/23638587/99150378-30a98a80-2662-11eb-88c0-89d96aac4894.png)

and this is the /crate page: 
![image](https://user-images.githubusercontent.com/23638587/99150382-3a32f280-2662-11eb-996f-7e3ede6b6226.png)

**Comment by poliorcetics** [comment]
I looked at both but I thought it was just another look for the docs, not another type of pages entirely 😅
