### ISSUE TITLE
If a favored url is converted to the current crate, use `crate::` instead

### ISSUE THREAD

**Issue by jyn514** [poliorcetics/cargo-intraconv#32]
```diff
-//! [docs-url]: https://docs.rs/tracing-serde
+//! [docs-url]: tracing_serde
```
```
warning: unresolved link to `tracing_serde`
 --> tracing-serde/src/lib.rs:9:17
  |
9 | //! [docs-url]: tracing_serde
  |                 ^^^^^^^^^^^^^ no item named `tracing_serde` in scope
```
Instead it should be `[docs-url]: crate`.

**Comment by poliorcetics** [comment]
This is caused by https://github.com/poliorcetics/cargo-intraconv/blob/master/src/lib.rs#L100-L107. I will try to fix it after the other issues are done.

**Comment by jyn514** [comment]
> This is caused by https://github.com/poliorcetics/cargo-intraconv/blob/master/src/lib.rs#L100-L107

Hmm, I don't see how that's related to the bug? The issue is that crates don't know their own name, so although you would think converting `docs.rs/x` to `x` is always correct, it causes an error when the link is in `x` itself. `intraconv` is detecting the name of the crate fine.

**Comment by poliorcetics** [comment]
The lines I noted associate a path and the crate name for that path. The way I wrote them is obviously broken ^^ because they don't do it properly: further down (in `src/link_parts.rs`) when a crate is found in a docs.rs link, `crate(::)?` is used correctly, I'll push a test for that.

**Comment by poliorcetics** [comment]
This should work correctly now 😄 !
