### ISSUE TITLE
Take backticks into account when removing links that are the same

### ISSUE THREAD

**Issue by jyn514** [poliorcetics/cargo-intraconv#33]
``[`tracing`][tracing]`` could just be ``[`tracing`]``.

**Comment by poliorcetics** [comment]
Is this specific to `rustdoc` ? The following produces two different links:

```
[`a`][a] or [`a`].

[a]: https://github.com
[`a`]: https://docs.rs
```

**Comment by poliorcetics** [comment]
And since `intraconv` doesn't have a lot of information about the links and their relationship between each other, I don't think this is feasible.

**Comment by jyn514** [comment]
Oh I see - you don't know whether `[a]` is a reference link (`[a]: example.com`) or a shortcut link to the rust path `a`. Yeah I can see how that's hard.
