### ISSUE TITLE
Ignore file compares the whole line, not the link

### ISSUE THREAD

**Issue by jyn514** [poliorcetics/cargo-intraconv#38]
I have an idea for how to fix this and I'm interested in working on this myself.

Currently, this does nothing:
```toml
[ignore]
"`handle_alloc_error`" = ["../../alloc/alloc/fn.handle_alloc_error.html"]
```
because intra-conv is looking at the whole line:

```
[src/config_file.rs:80] name = "    /// [`handle_alloc_error`]: "
[src/config_file.rs:80] value = "../../alloc/alloc/fn.handle_alloc_error.html"
core: alloc/global.rs
=====

   89:  "    /// [`handle_alloc_error`]: ../../alloc/alloc/fn.handle_alloc_error.html"
        "    /// [`handle_alloc_error`]: super::super::alloc::alloc::handle_alloc_error()"
```

**Comment by jyn514** [comment]
Ok I take it back I have no idea how to fix this :laughing: originally I thought I could just calls `link_parts` a little earlier and compare that:

https://github.com/poliorcetics/cargo-intraconv/blob/bb1b9127ba8a3ecb3862748193d929668cfc64bc/src/candidate.rs#L96

but that doesn't actually look at the header, it looks at the link. I don't know if the header is ever actually parsed?

**Comment by poliorcetics** [comment]
This is strange, I thought I had a test for that case. Obviously not !

Don't hesitate to submit a fix if you find the reason else I'll work on it before the week is over. 😄

**Comment by poliorcetics** [comment]
> `[src/config_file.rs:80] name = "    /// [`handle_alloc_error`]: "`

Ah well, I think I know where I'm doing my comparison wrong.

> I don't know if the header is ever actually parsed

It's not used beyond comparison so it's cheaper to not split it in three. I have an idea on how to fix it.

**Comment by poliorcetics** [comment]
The issue should be fixed now, it was a completely silly mistake on my part.
