### ISSUE TITLE
Feature request: remove links that are identical to the reference text

### ISSUE THREAD

**Issue by jyn514** [poliorcetics/cargo-intraconv#6]
```
-/// [non_blocking]: ./non_blocking/index.html
+/// [non_blocking]: non_blocking
```

**Comment by jyn514** [comment]
This could also be extended to handle backticks:

```
[`non_blocking`]: non_blocking
```

**Comment by poliorcetics** [comment]
Backticks are easy to handle, but does `[non_blocking]: non_blocking` correctly link to the module index ?

**Comment by jyn514** [comment]
That seems like a separate issue? The link will go to `non_blocking` whether or not you remove the link, `intraconv` doesn't have scoping information and can't fix that either way.

**Comment by poliorcetics** [comment]
On the most recent push, local paths should be removed properly, I have to write more tests to ensure this never changes though
